question_data = {
    {"category": "Science: Computers",
     "type": "multiple",
     "difficulty": "easy",
     "question": "When Gmail first launched, how much storage did it provide for your email?",
     "correct_answer": "1GB",
     "incorrect_answers": ["512MB", "5GB", "Unlimited"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "HTML is what type of language?", "correct_answer": "Markup Language",
     "incorrect_answers": ["Macro Language", "Programming Language", "Scripting Language"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "Which computer hardware device provides an interface for all other connected devices to communicate?",
     "correct_answer": "Motherboard",
     "incorrect_answers": ["Central Processing Unit", "Hard Disk Drive", "Random Access Memory"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In the programming language Java, which of these keywords would you put on a variable to make sure it doesn&#039;t get modified?",
     "correct_answer": "Final", "incorrect_answers": ["Static", "Private", "Public"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What is the code name for the mobile operating system Android 7.0?", "correct_answer": "Nougat",
     "incorrect_answers": ["Ice Cream Sandwich", "Jelly Bean", "Marshmallow"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "How many kilobytes in one gigabyte (in decimal)?", "correct_answer": "1000000",
     "incorrect_answers": ["1024", "1000", "1048576"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In &quot;Hexadecimal&quot;, what color would be displayed from the color code? &quot;#00FF00&quot;?",
     "correct_answer": "Green", "incorrect_answers": ["Red", "Blue", "Yellow"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
                                       "question": "In computing, what does MIDI stand for?",
                                       "correct_answer": "Musical Instrument Digital Interface",
                                       "incorrect_answers": ["Musical Interface of Digital Instruments",
                                                             "Modular Interface of Digital Instruments",
                                                             "Musical Instrument Data Interface"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What does the computer software acronym JVM stand for?", "correct_answer": "Java Virtual Machine",
     "incorrect_answers": ["Java Vendor Machine", "Java Visual Machine", "Just Virtual Machine"]}

}
